### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by cloutier** [weifund/weifund-contracts#11]
Please add an open-source license so that others will be able to reuse and deploy your code. I recommend the [GPLv3](https://www.gnu.org/licenses/gpl.html) if you don't have any favorite license.

**Comment by SilentCicero** [comment]
@cloutier accidental delete ;) -- https://github.com/weifund/weifund-contracts/blob/master/LICENSE

**Comment by cloutier** [comment]
Perfect, thank you! :smile:
