### ISSUE TITLE
Fallback functions and Out of Gas

### ISSUE THREAD

**Issue by ethers** [weifund/weifund-contracts#2]
Example, has this been tested?
https://github.com/WeiFund/weifund-contracts/blob/5f082c563c45819b5b8d86ee73fb9006321aa45a/contracts/CampaignAccount.sol#L197-L198

From readme:
CampaignAccount.sol ... This contract is mainly to utilize solidities fallback method, and redirect funds from a single address to a campaign hosted on the WeiFund core contract.

But this doesn't seem possible since fallback functions have very limited gas.

**Comment by SilentCicero** [comment]
@ethers we are doing a different design, all these contracts will be changed soon. And yes, your right re:  fallback function.

**Comment by SilentCicero** [comment]
See: https://github.com/WeiFund/weifund-contracts/tree/master/contracts-latest -- for the latest designs we are working on.

**Comment by ethers** [comment]
https://github.com/WeiFund/weifund-contracts/blob/master/contracts-latest/Campaign.sol#L15-L19
no need for fallback function; just use the actual function.

**Comment by SilentCicero** [comment]
@ethers the fallback function allows anyone to just send ether to this address. I think it is worth having here.

**Comment by ethers** [comment]
"best practices" are becoming clearer and non-trivial fallback function is discouraged because anyone that "just send ether to this address" should just use `send()` and then the FF will not have enough gas, so people can't use `send()`...
