### ISSUE TITLE
Consider using TokenFactory

### ISSUE THREAD

**Issue by ethers** [weifund/weifund-contracts#3]
Consider refactoring to leverage https://media.consensys.net/2016/06/16/how-to-create-your-own-tokens-deployed

**Comment by SilentCicero** [comment]
@ethers yes, I'm talking it over with Simon. I want to use the HumanStandardFactory if possible.

**Comment by SilentCicero** [comment]
@ethers using HumanStandardToken as of https://github.com/weifund/weifund-contracts/commit/cdd775112e493c9ec9a88f152e717380792ec0e1

**Comment by ethers** [comment]
but where is the token being created?  (or the factory being invoked?)
