### ISSUE TITLE
Cannot install or build from github repo as is

### ISSUE THREAD

**Issue by maurelian** [weifund/weifund-contracts#4]
## Issue Type

- [X] Bug
- [ ] Feature

## Description

1. The current script configuration in the `package.json` prevents building of this package. 
2. Resolving that, there appear to be some important files missing from the `/src/lib` directory.

## Steps to reproduce (first issue)

1. Clone a fresh copy of the repo
2. Run `npm install` that will return linter errors of the format: 
    
```bash
/Users/primary/Projects/weifund-project/weifund-contracts/internals/scripts/testContributionEthjs.js 
4:27  error    Unable to resolve path to module '../../src/lib/contracts.json'  import/no-unresolved
```

I was able to partially resolve the issue with this change: https://github.com/maurelian/weifund-contracts/commit/3ada2fda2a553c64fd9bf28be6e9bc07fc53846c, which moves linting and (most) testing to after the build steps. 

## Steps to reproduce (next issue)

After the previous fix above:

1. Run `npm install`
2. This time the contracts build successfully, but eventually I run into:

```

Error: while writting output JSON file ./src/lib/contracts.json: Error: ENOENT: no such file or directory, open '/Users/primary/temp/weifund-contracts/src/lib/contracts.json'
Error: while writting output JSON file ./src/lib/contracts.json: Error: ENOENT: no such file or directory, open '/Users/primary/temp/weifund-contracts/src/lib/contracts.json'
    at fs.writeFile (/Users/primary/temp/weifund-contracts/node_modules/wafr/bin/wafr.js:54:13)
    at fs.js:1305:7
    at FSReqWrap.oncomplete (fs.js:123:15)
```

I can get past this just by running `mkdir lib`. but then I run into an issue with this import:

https://github.com/weifund/weifund-contracts/blob/master/src/index.js#L2

**Possible solution**: Maybe everyone already working on this has some files in /src/lib/ that haven't been checked in since updates were made to the gitignore file?

# Versions

* node v6.5.0
* npm  v3.10.3

**Comment by SilentCicero** [comment]
will fix, thanks john @maurelian

**Comment by SilentCicero** [comment]
Should be fixed in commit https://github.com/weifund/weifund-contracts/commit/9b98cf8a2d4c690d320198e1c006ce269ecdbf3d
