### ISSUE TITLE
Unhandled .call

### ISSUE THREAD

**Issue by ethers** [weifund/weifund-contracts#4]
https://github.com/WeiFund/weifund-contracts/blob/4f009381cf3db20e76f8d1154fb15a38c21aaad2/contracts/CategoryAuction.sol#L260

Return value is not checked; the Forwarded event can be triggered even though the forward didn't happen.

**Comment by SilentCicero** [comment]
@ethers great find, I haven't addressed this set of contracts yet. I'll address in the `contracts-latest`
