### ISSUE TITLE
Handle .send

### ISSUE THREAD

**Issue by ethers** [weifund/weifund-contracts#5]
Return value of .send should be checked and handled, or commented why it is not necessary or undesired.
Example:
https://github.com/WeiFund/weifund-contracts/blob/master/contracts-latest/Campaign.sol#L50

**Comment by SilentCicero** [comment]
I haven't done the check and handle for this, I'm experimenting with a ClaimProxy model. It creates a contract that is simple, and sends money to that contract. The contract has no outward call capability that can interact with the Campaign contract. Just an experiment at this point. These contracts have not been vetted, and are in the design phase. Thanks so much dude, I'll keep you posted on when we audit this. Please keep making issues if you see any big red flags.

**Comment by SilentCicero** [comment]
https://github.com/WeiFund/weifund-contracts/blob/master/contracts-latest/Campaign.sol#L57 -- here I'm checking send for falseness, then throwing an error if it is infact false. Thoughts? @ethers 

That, plus my ClaimProxy, limits the interaction between other contracts and the campaign contract.

**Comment by ethers** [comment]
I see https://github.com/WeiFund/weifund-contracts/blob/master/contracts-latest/Campaign.sol#L61-L65 and it looks good.

**Comment by SilentCicero** [comment]
Send is handled with conditionals and proxy.
