### ISSUE TITLE
Use a state machine

### ISSUE THREAD

**Issue by ethers** [weifund/weifund-contracts#8]
The modifiers `` are ad-hoc and an explicit state machine would probably clearer.

some example contracts: http://www.arijuels.com/wp-content/uploads/2016/06/Setting-Standards-for-Altering-and-Undoing-Smart-Contracts.docx

Here are the current weifund modifiers:
```
  modifier reachedFundingGoal {
    if(this.balance >= fundingGoal) {
      _
    }
  }

  modifier pastExpiry {
    if(now > expiry) {
      _
    }
  }

  modifier unreachedFundingGoal {
    if(this.balance < fundingGoal) {
      _
    }
  }

  modifier senderClaimNotMade {
    if(claimMade[msg.sender] == false) {
      _
    }
  }
```

**Comment by SilentCicero** [comment]
@ethers addressed in the latest StandardCampaign contracts.

**Comment by SilentCicero** [comment]
Implemented.
